version: "3.1"
services:
  mysql:
    build: docker/mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "database_test"
    volumes:
      - ./docker/mysql_data:/var/lib/mysql
    restart: always
    networks:
      docker_mysql_network:

networks:
  docker_mysql_network:
    driver: bridge